/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gomitas;

import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author lalqu
 */
public class Bodega extends javax.swing.JPanel {
    
    public void llenarBodega(String S)
    {
        String SQL = "Select sum(Cantidad) from Bodega where Ingrediente = \""+S+"\"";
        try
        {
            c.con = DriverManager.getConnection(c.cadena, c.usuario, c.contrasenia);
            Statement stmt;
            ResultSet rs = null;
            
            stmt = c.con.createStatement();
            rs = stmt.executeQuery(SQL);
            
            if("Agua".equals(S))
            {
                if(rs.next())
                {
                    txtAgua.setText(rs.getString("sum(Cantidad)"));
                }
            }
            else if("Leche".equals(S))
            {
                if(rs.next())
                {
                    txtAlmidon.setText(rs.getString("sum(Cantidad)"));
                }
            }
            else if("Azucar".equals(S))
            {
                if(rs.next())
                {
                    txtAzucar.setText(rs.getString("sum(Cantidad)"));
                }
            }
            else if("Palitos_madera".equals(S))
            {
                if(rs.next())
                {
                    txtCera.setText(rs.getString("sum(Cantidad)"));
                }
            }
            else if("Saborizantes_agua".equals(S))
            {
                if(rs.next())
                {
                    txtGrenetina.setText(rs.getString("sum(Cantidad)"));
                }
            }
             else if("Saborizantes_leche".equals(S))
            {
                if(rs.next())
                {
                    txtJarabe.setText(rs.getString("sum(Cantidad)"));
                }
            }
            
        }catch(Exception e){
            System.out.println(e);
        }
    }
    
    /**
     * Creates new form Bodega
     */
    public Bodega() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        LbAgua = new javax.swing.JLabel();
        LbAzucar = new javax.swing.JLabel();
        LbGrenetina = new javax.swing.JLabel();
        LbJarabe = new javax.swing.JLabel();
        LbAlmidon = new javax.swing.JLabel();
        LbCera = new javax.swing.JLabel();
        txtAgua = new javax.swing.JTextField();
        txtAzucar = new javax.swing.JTextField();
        txtGrenetina = new javax.swing.JTextField();
        txtJarabe = new javax.swing.JTextField();
        txtAlmidon = new javax.swing.JTextField();
        txtCera = new javax.swing.JTextField();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setBackground(new java.awt.Color(232, 222, 148));

        LbAgua.setText("Agua");

        LbAzucar.setText("Leche");

        LbGrenetina.setText("Azucar");

        LbJarabe.setText("Palitos de madera");

        LbAlmidon.setText("Saborizantes agua");

        LbCera.setText("Saborizantes leche");

        txtAgua.setEditable(false);

        txtAzucar.setEditable(false);

        txtGrenetina.setEditable(false);

        txtJarabe.setEditable(false);

        txtAlmidon.setEditable(false);

        txtCera.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(LbAgua))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LbAzucar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LbGrenetina))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LbJarabe))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LbAlmidon))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LbCera)))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAlmidon, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCera, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJarabe, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGrenetina, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAzucar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbAgua)
                    .addComponent(txtAgua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAzucar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbAzucar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGrenetina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbGrenetina))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJarabe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbJarabe))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlmidon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbAlmidon))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbCera))
                .addGap(0, 72, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    Conectar c = new Conectar();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbAgua;
    private javax.swing.JLabel LbAlmidon;
    private javax.swing.JLabel LbAzucar;
    private javax.swing.JLabel LbCera;
    private javax.swing.JLabel LbGrenetina;
    private javax.swing.JLabel LbJarabe;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextField txtAgua;
    public javax.swing.JTextField txtAlmidon;
    public javax.swing.JTextField txtAzucar;
    public javax.swing.JTextField txtCera;
    public javax.swing.JTextField txtGrenetina;
    public javax.swing.JTextField txtJarabe;
    // End of variables declaration//GEN-END:variables
}
