/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gomitas;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author lalqu
 */
public class Cliente extends javax.swing.JPanel {

    public void cliente()
    {
        try
        {
            c.con = DriverManager.getConnection(c.cadena, c.usuario, c.contrasenia);
            PreparedStatement Y = c.con.prepareStatement("{call  RCliente (?,?,?)}");
                Y.setInt(1, Integer.parseInt(txtIDCliente.getText()));
                Y.setString(2, txtNombre.getText());
                Y.setString(3, txtApellido.getText());
            Y.execute();
            LbEstado.setText("Registro exitoso");
        }catch(Exception e){
            LbEstado.setText("Ocurrio un error...");
            System.out.println(e);
        }
    }
    
    public void Editar()
    {
        try
        {
            c.con = DriverManager.getConnection(c.cadena, c.usuario, c.contrasenia);
            String SQL =  "Select ID_Cliente from Cliente";
            Statement stmt;
            ResultSet rs = null;
            stmt = c.con.createStatement();
            rs = stmt.executeQuery(SQL);
            
            while(rs.next())
            {
                cbEditar.addItem(rs.getString("ID_Cliente"));
            }
            
        }catch(Exception e)
        {
            System.out.println(e);
        }
    }
    
    public void muestra(int S)
    {
        try
        {
            c.con = DriverManager.getConnection(c.cadena, c.usuario, c.contrasenia);
            String SQL =  "Select Nombre_Cliente from Cliente where ID_Cliente=" + S;
            Statement stmt;
            ResultSet rs = null;
            stmt = c.con.createStatement();
            rs = stmt.executeQuery(SQL);
            
            String SQ =  "Select Apellido_Cliente from Cliente where ID_Cliente=" + S;
            Statement stm;
            ResultSet r = null;
            stm = c.con.createStatement();
            r = stm.executeQuery(SQ);
            
            int o = -1;
            String NC="",AC="";
            
            while(rs.next())
            {
                NC =rs.getString("Nombre_Cliente");
            }
            while(r.next())
            {
                AC =r.getString("Apellido_Cliente");
            }
            o = JOptionPane.showConfirmDialog(null,"ID: "+ S +"\nNombre: "+ NC+"\nApellido: "+ AC, "Confirme la edicion", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if(o == 0)
            {
                NC = JOptionPane.showInputDialog(null,"Nombre actual:     "+NC+"\nIngrese el nombre del cliente","Nombre del cliente",JOptionPane.INFORMATION_MESSAGE);
                AC = JOptionPane.showInputDialog(null,"Apellido actual:     "+AC+"\nIngrese el Apellido del cliente","Apellido del cliente",JOptionPane.INFORMATION_MESSAGE);
                
                PreparedStatement Y = c.con.prepareStatement("{call  MCliente (?,?,?)}");
                Y.setInt(1, S);
                Y.setString(2, NC);
                Y.setString(3, AC);
                Y.execute();
                JOptionPane.showMessageDialog(null, "Actualizacion exitosa");
            }
        }catch(Exception e)
        {
            System.out.println(e);
        }
    }
    
    /**
     * Creates new form Cliente
     */
    public Cliente() {
        initComponents();
        txtIDCliente.setText("60");
        LbBorrar.setVisible(false);
        cbEditar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbIDCliente = new javax.swing.JLabel();
        LbNombre = new javax.swing.JLabel();
        LbApellido = new javax.swing.JLabel();
        txtIDCliente = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        LbImg = new javax.swing.JLabel();
        LbEstado = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        LbBorrar = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        cbEditar = new javax.swing.JComboBox<>();
        btnEditar1 = new javax.swing.JButton();
        LbApellido1 = new javax.swing.JLabel();
        txtApellido1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(151, 242, 153));

        LbIDCliente.setText("ID del cliente");

        LbNombre.setText("Nombre");

        LbApellido.setText("Apellido");

        LbImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cliente.jpg"))); // NOI18N

        LbEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        LbBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/goma.jpg"))); // NOI18N
        LbBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LbBorrarblanco(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarCb(evt);
            }
        });

        cbEditar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        cbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEditarActionPerformed(evt);
            }
        });

        btnEditar1.setText("Eliminar");
        btnEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar1ActionPerformed(evt);
            }
        });

        LbApellido1.setText("ID de cliente para borrar");

        txtApellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellido1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LbApellido1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LbEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(cbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbIDCliente)
                            .addComponent(LbNombre)
                            .addComponent(LbApellido))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIDCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtNombre)
                            .addComponent(txtApellido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(LbImg)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEditar)
                        .addGap(38, 38, 38)
                        .addComponent(btnGuardar)
                        .addGap(29, 29, 29)
                        .addComponent(btnEditar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LbBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbIDCliente)
                            .addComponent(txtIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbApellido)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(LbImg, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(cbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbApellido1)
                            .addComponent(LbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGuardar)
                        .addComponent(btnEditar)
                        .addComponent(btnEditar1))
                    .addComponent(LbBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        cliente();
        LbBorrar.setVisible(true);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void LbBorrarblanco(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbBorrarblanco
        // TODO add your handling code here:
        txtIDCliente.setText("60");
        txtNombre.setText("");
        txtApellido.setText("");
        LbEstado.setText("");
        LbBorrar.setVisible(false);
    }//GEN-LAST:event_LbBorrarblanco

    private void mostrarCb(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarCb
        // TODO add your handling code here:
        cbEditar.setVisible(true);
        JOptionPane.showMessageDialog(null,"Solo puede editar el nombre y apellido del cliente","Advertencia",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_mostrarCb

    private void cbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEditarActionPerformed
        // TODO add your handling code here:
        muestra(Integer.parseInt(cbEditar.getSelectedItem().toString()));
    }//GEN-LAST:event_cbEditarActionPerformed

    private void btnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar1ActionPerformed
        try
        {
            c.con = DriverManager.getConnection(c.cadena, c.usuario, c.contrasenia);
            PreparedStatement Y = c.con.prepareStatement("{call  BCliente (?)}");
                Y.setInt(1, Integer.parseInt(txtApellido1.getText()));
            Y.execute();
            LbEstado.setText("Borrado exitoso");
        }catch(Exception e){
            LbEstado.setText("Ocurrio un error...");
            System.out.println(e);
        }
    }//GEN-LAST:event_btnEditar1ActionPerformed

    private void txtApellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellido1ActionPerformed

    Conectar c = new Conectar();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbApellido;
    private javax.swing.JLabel LbApellido1;
    private javax.swing.JLabel LbBorrar;
    private javax.swing.JLabel LbEstado;
    private javax.swing.JLabel LbIDCliente;
    private javax.swing.JLabel LbImg;
    private javax.swing.JLabel LbNombre;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEditar1;
    private javax.swing.JButton btnGuardar;
    public javax.swing.JComboBox<String> cbEditar;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtIDCliente;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
