/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gomitas;

import java.awt.event.ActionEvent;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;


/**
 *
 * @author lalqu
 */
public class Proveedor extends javax.swing.JPanel {
    
    public void provee()
    {
        try
        {
            c.con = DriverManager.getConnection(c.cadena, c.usuario, c.contrasenia);
            PreparedStatement Y = c.con.prepareStatement("{call  Agregar_Proveedores (?,?)}");
                Y.setInt(1, Integer.parseInt(txtIDProveedor.getText()));
                Y.setString(2, txtNProveedor.getText());
            Y.execute();
            LbEstado.setText("Registro exitoso");
        }catch(Exception e){
            LbEstado.setText("Ocurrio un error...");
            System.out.println(e);
        }
    }
    
    public void Editar()
    {
        try
        {
            c.con = DriverManager.getConnection(c.cadena, c.usuario, c.contrasenia);
            String SQL =  "Select ID_Proveedor from Proveedores";
            Statement stmt;
            ResultSet rs = null;
            stmt = c.con.createStatement();
            rs = stmt.executeQuery(SQL);
            
            while(rs.next())
            {
                cbEditar.addItem(rs.getString("ID_Proveedor"));
            }
            
        }catch(Exception e)
        {
            System.out.println(e);
        }
    }
    
    public void muestra(int S)
    {
        try
        {
            c.con = DriverManager.getConnection(c.cadena, c.usuario, c.contrasenia);
            String SQL =  "Select Nombre_Proveedor from Proveedores where ID_Proveedor=" + S;
            Statement stmt;
            ResultSet rs = null;
            stmt = c.con.createStatement();
            rs = stmt.executeQuery(SQL);
            int o = -1;
            String NP="";
            
            while(rs.next())
            {
                NP = rs.getString("Nombre_Proveedor");
            }
            o = JOptionPane.showConfirmDialog(null, "ID: "+S +"\nNombre: "+ NP, "Confirme la edicion", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if(o == 0)
            {
                NP = JOptionPane.showInputDialog(null,"Nombre actual:     "+NP+"\nIngrese el nombre del proveedor","Nombre del proveedor",JOptionPane.INFORMATION_MESSAGE);

                PreparedStatement Y = c.con.prepareStatement("{call  MProveedor (?,?)}");
                Y.setInt(1, S);
                Y.setString(2, NP);
                Y.execute();
                JOptionPane.showMessageDialog(null, "Actualizacion exitosa");
            }
        }catch(Exception e)
        {
            System.out.println(e);
        }
    }
    
    public Proveedor() {
        initComponents();
        txtIDProveedor.setText("10");
        LbBorrar.setVisible(false);
        cbEditar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEliminar = new javax.swing.JButton();
        LbIDProveedor = new javax.swing.JLabel();
        LbNProveedor = new javax.swing.JLabel();
        txtIDProveedor = new javax.swing.JTextField();
        txtNProveedor = new javax.swing.JTextField();
        LbProveedor = new javax.swing.JLabel();
        LbEstado = new javax.swing.JLabel();
        btnGProveedor = new javax.swing.JButton();
        LbBorrar = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        cbEditar = new javax.swing.JComboBox<>();
        txtNProveedor1 = new javax.swing.JTextField();
        LbNProveedor1 = new javax.swing.JLabel();
        btnEditar1 = new javax.swing.JButton();

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(255, 124, 5));
        setPreferredSize(new java.awt.Dimension(400, 300));

        LbIDProveedor.setText("ID del proveedor");

        LbNProveedor.setText("Nombre del proveedor");

        LbProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PROVEEDORES.png"))); // NOI18N

        LbEstado.setBackground(new java.awt.Color(0, 0, 0));
        LbEstado.setForeground(new java.awt.Color(255, 255, 255));
        LbEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnGProveedor.setText("Guardar");
        btnGProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGProveedorActionPerformed(evt);
            }
        });

        LbBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/goma.jpg"))); // NOI18N
        LbBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                blanco(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                llenaCb(evt);
            }
        });

        cbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEditarActionPerformed(evt);
            }
        });

        txtNProveedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNProveedor1ActionPerformed(evt);
            }
        });

        LbNProveedor1.setText("ID del proveedor");

        btnEditar1.setText("Eliminar");
        btnEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LbIDProveedor)
                        .addGap(50, 50, 50)
                        .addComponent(txtIDProveedor)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(cbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LbEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LbNProveedor1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(btnGProveedor)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbNProveedor)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(LbBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(btnEditar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNProveedor)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LbProveedor)
                                .addGap(40, 40, 40)
                                .addComponent(btnEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbIDProveedor)
                            .addComponent(txtIDProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbNProveedor)
                            .addComponent(txtNProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LbProveedor)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(LbBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnEditar1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LbNProveedor1)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnGProveedor)
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGProveedorActionPerformed
        provee();
        LbBorrar.setVisible(true);
    }//GEN-LAST:event_btnGProveedorActionPerformed

    private void blanco(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blanco
        // TODO add your handling code here:
        txtIDProveedor.setText("10");
        txtNProveedor.setText("");
        LbEstado.setText("");
        LbBorrar.setVisible(false);
        cbEditar.setVisible(false);
    }//GEN-LAST:event_blanco

    private void cbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEditarActionPerformed
        // TODO add your handling code here:
        muestra(Integer.parseInt(cbEditar.getSelectedItem().toString()));
    }//GEN-LAST:event_cbEditarActionPerformed

    private void llenaCb(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_llenaCb
        // TODO add your handling code here:
        cbEditar.setVisible(true);
        mostrarCb();
        JOptionPane.showMessageDialog(null,"Solo puede editar el nombre del proveedor","Advertencia",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_llenaCb

    private void txtNProveedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNProveedor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNProveedor1ActionPerformed

    private void btnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar1ActionPerformed
       try
        {
            c.con = DriverManager.getConnection(c.cadena, c.usuario, c.contrasenia);
            PreparedStatement Y = c.con.prepareStatement("{call  BProveedor (?)}");
                Y.setInt(1, Integer.parseInt(txtNProveedor1.getText()));
            Y.execute();
            LbEstado.setText("Borrado exitoso");
        }catch(Exception e){
            LbEstado.setText("Ocurrio un error...");
            System.out.println(e);
        }
    }//GEN-LAST:event_btnEditar1ActionPerformed

    public void mostrarCb()
    {
        Combos mcb = new Combos();
        
        DefaultComboBoxModel cModel = mcb.EProveedor();
        cbEditar.setModel(cModel);
    }
    
    Conectar c = new Conectar();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbBorrar;
    private javax.swing.JLabel LbEstado;
    private javax.swing.JLabel LbIDProveedor;
    private javax.swing.JLabel LbNProveedor;
    private javax.swing.JLabel LbNProveedor1;
    private javax.swing.JLabel LbProveedor;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEditar1;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGProveedor;
    public javax.swing.JComboBox<String> cbEditar;
    private javax.swing.JTextField txtIDProveedor;
    private javax.swing.JTextField txtNProveedor;
    private javax.swing.JTextField txtNProveedor1;
    // End of variables declaration//GEN-END:variables
}
