/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gomitas;

import java.awt.Image;
import java.sql.DriverManager;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author lalqu
 */
public class Receta_Stock extends javax.swing.JPanel {

    String Goma;
    
    public void cliente(int auxiliar)
    {
        
        try
        {
            c.con = DriverManager.getConnection(c.cadena, c.usuario, c.contrasenia);
            PreparedStatement Y = c.con.prepareStatement("{call  RStock (?,?,?)}");
                Y.setInt(1, auxiliar);
                Y.setString(2, txtGomita.getText());
                Y.setInt(3, Integer.parseInt(txtCantidad.getText()));
            Y.execute();
            
            
            
            PreparedStatement S = c.con.prepareStatement("{call  RReceta (?,?,?,?,?)}");
                S.setInt(1, Integer.parseInt(txtIDC.getText()));
                S.setInt(2, 30);
                S.setInt(3, auxiliar);
                S.setString(4, txtGomita.getText());
                S.setInt(5, Integer.parseInt(txtCantidad.getText()));
            S.execute();
            
            LbEstado.setText("Registro exitoso");
        }catch(Exception e){
            LbEstado.setText("Ocurrio un error...");
            System.out.println(e);
            LbBorrar2.setVisible(true);
        }
        Stock.cbBodega.addItem(String.valueOf(auxiliar));
    }
    
    public void complemento()
    {
        btnCrear.setVisible(false);
        txtLote.setEditable(false);
    }
    
    public Icon img(String Ch)
    {
        ImageIcon image = new ImageIcon("src/Imagenes/"+Ch);
            Icon icon = new ImageIcon(image.getImage().getScaledInstance(LbMuestra.getWidth(), LbMuestra.getHeight(), Image.SCALE_DEFAULT));
            return icon;
    }
    
    public void muestra(int S)
    {
        try
        {
            c.con = DriverManager.getConnection(c.cadena, c.usuario, c.contrasenia);
            String SQL =  "Select Cantida from Receta where Lot_Stock=" + S;
            Statement stmt;
            ResultSet rs = null;
            stmt = c.con.createStatement();
            rs = stmt.executeQuery(SQL);
            
            String SQ =  "Select Paleta from Receta where Lot_Stock=" + S;
            Statement stm;
            ResultSet r = null;
            stm = c.con.createStatement();
            r = stm.executeQuery(SQ);
            
            int o, C=0;
            String G = "";
            
            while(rs.next())
            {
                C =Integer.parseInt(rs.getString("Cantida"));
            }
            while(r.next())
            {
                G =r.getString("Paleta");
            }
            o = JOptionPane.showConfirmDialog(null,"Lote: "+ S +"\nCantidad: "+ C+"\nPaleta: "+G, "Confirme la edicion", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if(o == 0)
            {
                C = Integer.parseInt(JOptionPane.showInputDialog(null,"Cantidad actual:     "+C+"\nIngrese la cantidad","Cantidad de produccion",JOptionPane.INFORMATION_MESSAGE));
                
                PreparedStatement Y = c.con.prepareStatement("{call  MReceta (?,?)}");
                Y.setInt(1, S);
                Y.setInt(2, C);
                Y.execute();
                JOptionPane.showMessageDialog(null, "Actualizacion exitosa");
            }
        }catch(Exception e)
        {
            System.out.println(e);
        }
    }
    
    /**
     * Creates new form Receta_Stock
     */
    
    public Receta_Stock() {
        
        initComponents();
        
        LbIDCocinero.setVisible(false);
        LbCantidadG.setVisible(false);
        btnProducir.setVisible(false);
        txtIDC.setVisible(false);
        txtCantidad.setVisible(false);
        LbBorrar2.setVisible(false);
        LbPasa.setVisible(false);
        cbEditar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbLote = new javax.swing.JLabel();
        txtLote = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        LbIDCocinero = new javax.swing.JLabel();
        LbTGomita = new javax.swing.JLabel();
        LbCantidadG = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        LbMuestra = new javax.swing.JLabel();
        btnProducir = new javax.swing.JButton();
        LbBorrar2 = new javax.swing.JLabel();
        LbEstado = new javax.swing.JLabel();
        LbPasa = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        cbEditar = new javax.swing.JComboBox<>();
        txtGomita = new javax.swing.JTextField();
        txtIDC = new javax.swing.JTextField();

        setBackground(new java.awt.Color(246, 235, 128));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbLote.setText("Lote");
        add(LbLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));
        add(txtLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 90, -1));

        btnCrear.setText("Crear lote");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearLote(evt);
            }
        });
        add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        LbIDCocinero.setText("ID del cocinero");
        add(LbIDCocinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        LbTGomita.setText("Paleta");
        add(LbTGomita, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 20));

        LbCantidadG.setText("Cantidad");
        add(LbCantidadG, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        txtCantidad.setToolTipText("Bolsas de 500gr");
        add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 90, -1));

        LbMuestra.setBackground(new java.awt.Color(255, 255, 255));
        LbMuestra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cocina.jpg"))); // NOI18N
        add(LbMuestra, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 150, 150));

        btnProducir.setText("Producir");
        btnProducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completarProceso(evt);
            }
        });
        add(btnProducir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        LbBorrar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/goma.jpg"))); // NOI18N
        LbBorrar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LbBorrar2blanco(evt);
            }
        });
        add(LbBorrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        LbEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(LbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 200, 400, -1));

        LbPasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pasa.jpg"))); // NOI18N
        LbPasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ok(evt);
            }
        });
        add(LbPasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 30, 30));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarmostrarCb(evt);
            }
        });
        add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        cbEditar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        cbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEditarActionPerformed(evt);
            }
        });
        add(cbEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        txtGomita.setEditable(false);
        add(txtGomita, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 90, -1));

        txtIDC.setEditable(false);
        add(txtIDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 90, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void crearLote(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearLote
        // TODO add your handling code here:
        complemento();
        Goma = txtGomita.getText();
        LbBorrar2.setVisible(true);
        LbPasa.setVisible(true);
        JOptionPane.showMessageDialog(null, "Por favor revise la informacion introducida\nDe ser erronea, coloque el cursor sobre la goma para editar\nCaso contrario, use la palomita :D");
    }//GEN-LAST:event_crearLote

    private void completarProceso(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completarProceso
        // TODO add your handling code here:
        int auxiliar = Integer.parseInt(txtLote.getText());
        cliente(auxiliar);
        LbBorrar2.setVisible(true);
    }//GEN-LAST:event_completarProceso

    private void LbBorrar2blanco(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbBorrar2blanco
        // TODO add your handling code here:
        String C;
        
        txtCantidad.setText("");
        LbBorrar2.setVisible(false);
        txtLote.setText("");
        LbEstado.setText("");
        txtLote.setEditable(true);
        LbIDCocinero.setVisible(false);
        LbCantidadG.setVisible(false);
        btnProducir.setVisible(false);
        txtIDC.setVisible(false);
        txtCantidad.setVisible(false);
        LbBorrar2.setVisible(false);
        btnCrear.setVisible(true);
        LbPasa.setVisible(false);
        cbEditar.setVisible(false);
        
        C = txtGomita.getText();
        if(null != C)
        switch (C) {
            case "Paletas_agua" -> txtLote.setText("50");
            case "Palteas_leche" -> txtLote.setText("51");
            default -> {
            }
        }
    }//GEN-LAST:event_LbBorrar2blanco

    private void ok(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ok
        // TODO add your handling code here:
        
        LbMuestra.setVisible(true);
        LbIDCocinero.setVisible(true);
        LbTGomita.setVisible(true);
        LbCantidadG.setVisible(true);
        btnProducir.setVisible(true);
        txtIDC.setVisible(true);
        txtCantidad.setVisible(true);
        
        LbBorrar2.setVisible(false);
        LbPasa.setVisible(false);
    }//GEN-LAST:event_ok

    private void btnEditarmostrarCb(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarmostrarCb
        // TODO add your handling code here:
        cbEditar.setVisible(true);
        mostrarCbEditar();
        JOptionPane.showMessageDialog(null,"Solo puede editar la cantidad de produccion","Advertencia",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnEditarmostrarCb

    private void cbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEditarActionPerformed
        // TODO add your handling code here:
        muestra(Integer.parseInt(cbEditar.getSelectedItem().toString()));
    }//GEN-LAST:event_cbEditarActionPerformed

    public void mostrarCbEditar()
    {
        Combos mcb = new Combos();
        
        DefaultComboBoxModel cModel = mcb.EProducto();
        cbEditar.setModel(cModel);
    }
    
    Conectar c = new Conectar();
    Stock Stock = new Stock();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbBorrar2;
    private javax.swing.JLabel LbCantidadG;
    private javax.swing.JLabel LbEstado;
    private javax.swing.JLabel LbIDCocinero;
    private javax.swing.JLabel LbLote;
    public javax.swing.JLabel LbMuestra;
    private javax.swing.JLabel LbPasa;
    private javax.swing.JLabel LbTGomita;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnProducir;
    public javax.swing.JComboBox<String> cbEditar;
    private javax.swing.JTextField txtCantidad;
    public javax.swing.JTextField txtGomita;
    public javax.swing.JTextField txtIDC;
    public javax.swing.JTextField txtLote;
    // End of variables declaration//GEN-END:variables
}
